#!/usr/bin/env node
/*
 * Publish the league workbook to the site.
 *
 *   node tools/publish.js "C:\path\to\2026 Fall League.xlsx"   → writes data/league.js
 *   node tools/publish.js <file.xlsx> --push                    → … then git commit + push
 *
 * Only the parsed JSON is written. The workbook itself is never copied into the
 * repo (it is git-ignored) so that a filled-in "Player Contact Info" tab can never
 * end up on the public site.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const XLSX = require('xlsx');
const { parseWorkbook } = require('../js/parse.js');

const args = process.argv.slice(2);
const push = args.includes('--push');
const file = args.find((a) => !a.startsWith('--'));
if (!file) {
  console.error('Usage: node tools/publish.js <league.xlsx> [--push]');
  process.exit(1);
}
if (!fs.existsSync(file)) {
  console.error(`File not found: ${file}`);
  process.exit(1);
}

const root = path.join(__dirname, '..');
const wb = XLSX.readFile(file, { cellDates: false });
const data = parseWorkbook(XLSX, wb, { source: path.basename(file) });

const out = path.join(root, 'data', 'league.js');
// A .js file (not .json) so index.html also works when opened straight from disk.
fs.writeFileSync(out, `// Generated by tools/publish.js from "${path.basename(file)}" — do not edit by hand.\nwindow.LEAGUE_DATA = ${JSON.stringify(data, null, 1)};\n`);

// Cache-buster: stamp every asset reference in index.html so browsers (and GitHub
// Pages' 10-minute cache) pick up the new data instead of a stale copy.
const stamp = data.generatedAt.replace(/[-:TZ.]/g, '').slice(0, 12);
const indexPath = path.join(root, 'index.html');
fs.writeFileSync(indexPath, fs.readFileSync(indexPath, 'utf8').replace(/(.(?:js|css))?v=[^"']*/g, ));

const played = data.fixtures.filter((f) => f.played).length;
console.log(`${data.league} — ${data.season}`);
console.log(`  teams ${data.teams.length}, substitutes ${data.substitutes.length}, fixtures ${data.fixtures.length} (${played} played), weeks with sheets ${data.weeks.length}`);
console.log(`  standings: ${data.standings.map((s) => `${s.place}. ${s.team} ${s.teamPts}`).join(' · ')}`);
console.log(`→ ${path.relative(process.cwd(), out)}`);

if (push) {
  const week = Math.max(0, ...data.fixtures.filter((f) => f.played).map((f) => f.week));
  const msg = `Results through week ${week} (${data.source.replace(/"/g, '')})`;
  execSync('git add data/league.js index.html', { cwd: root, stdio: 'inherit' });
  execSync(`git commit -m "${msg}"`, { cwd: root, stdio: 'inherit' });
  execSync('git push', { cwd: root, stdio: 'inherit' });
  console.log('Pushed — GitHub Pages will update in a minute or two.');
}
